# 本文件严格区分参数的数据类型，比如 10.0 不能改成 10


[Camera]
#@bool 是否通过sn码查找相机,false则查找第0个
use_camera_sn = true
#@string 相机sn码
camera_sn = ""
#@bool 从MVS中导出的配置文件
use_config_from_file = false
#@string 文件夹中的路径
file_path = ""
#@bool 是否从camera.config中设置参数,会覆盖上文中file中的参数
use_camera_config = false

#可以填写MVS中的参数,但只支持int,double,bool类型
[Camera.config]



[Camera.record]
#@bool 是否开启内录
recording = false
fps = 15

[Serial]
port_name = "/dev/ttyUSB0"
baudrate =
data_print_debug =
ignore_crc =
#不接串口测试的虚拟数据
use_fake_serial_data =

[Serial.data]
yaw =
pitch =

